# User Preference 
Perefence: # Required 
  Search: Full stack, Django, REST Framework, Python, HTML, CSS, Bootstrap, JavaScript, jQuery,  
  Location: Remote, Norwich, Ipswich, Colechetser, London 
  Skills:  HTML, CSS, Bootstrap, JavaScript, jQuery, Postgres SQL, Django, REST Framework, Python  
  Exclude: Senioir, React, Lead, Manager, Marketing 
